export const PROJECTS = [
  "31N festival tower",
  "ALTA TOWER",
  "Al Inma Bank",
  "Alianz",
  "Amazon Tower",
  "Azrieli Spiral Tower",
  "Ascendes & ind proj",
  "Bugatti",
  "Burj 2020",
  "Burj Azizi SZR",
  "Burj vista",
  "Burj Binghatti",
  "Captial Jerusalem",
  "COMO Residences",
  "Crospy",
  "DIFC - 2024",
  "DMCC",
  "Dewa",
  "FGRF",
  "Four seasons",
  "G.M.I.C",
  "Guggenhein Cone 2",
  "Hail Water Tank Tower",
  "Hilton",
  "Imperial",
  "India",
  "JANGO Projects",
  "Jiddah Hospital",
  "Lusail plaza tower",
  "Masref al Rayyan",
  "Mercedes Benz Places",
  "Mixed used developement",
  "Mozoom tower",
  "NAPCO",
  "NPP64",
  "Oppera",
  "Oryx Tower",
  "Phoenix",
  "Queens boulevard",
  "ROVE HOME",
  "S-Tower Project",
  "SAFA 2",
  "SAFA ONE",
  "Security Force",
  "Ski Village",
  "Sky Rise",
  "Sky view",
  "Sofitel",
  "STC - ksa",
  "Trafalghar",
  "Vida Mall",
  "Wasal 2020",
  "Yacht Club",
];

export const SUPPLIERS = [
  "Avigiri",
  "ALUPCO",
  "AREXCO",
  "ELITE",
  "EASTERN ALUMINUM",
  "BALEXCO",
  "CANEX",
  "MADAR",
  "NAPCO",
  "SMS",
  "PMB",
  "ALTAISEER",
  "GRI",
  "TRC",
  "IRC",
  "KELEGENT",
  "PV-TECH",
  "YUANFA",
  "ALKAS",
  "SYSTRANS POLYMERS",
  "THERMOPLAST",
  "Techno form",
  "Viexal",
  "Vedali Hardware",
  "3H",
  "Ensinger",
];

export const SUPPLIER_ALIAS_GROUPS = new Map([
  ["EASTERN ALUMINUM", ["EASTERN ALUMINIUM", "EASTERN ALUMINUM"]],
  ["ELITE", ["ELITE EXTRUSUION", "ELITE EXTRUSAION", "ELITE"]],
  ["SMS", ["SCHIMMER METAL STANDARD", "SCHIMMER METAL STANDARD (SMS)", "SMS"]],
  ["GRI", ["GULF RUBBER INDUSTRIES ( GRI )", "GULF RUBBER INDUSTRIES", "GRI"]],
  ["TRC", ["TRC", "TECHNO RUBBER CO."]],
  ["IRC", ["IRC", "INTERNATIONAL RUBBER CO."]],
  ["KELEGENT", ["KELEGENT", "SHREE MAHAVIR METAL", "SHREE", "SHREE HAHAVIR METAL IND"]],
  [
    "PV-TECH",
    [
      "PV-TECH",
      "PV TECH",
      "POLYMER VISION TECHNOLOGY",
      "PV-TECH (POLYMER VISION TECHNOLOGY)",
    ],
  ],
  ["YUANFA", ["YUANFA", "WUHAN YUANFA", "WUHAN YUANFA (CHINA)"]],
]);

export const SYSTEMS = ["Tental", "Galene Next GTz", "Topaze"];
